---
title: "cross_validation"
author: "Xiaoni Xu"
date: "2024-11-12"
output: html_document
---
Load key packages
```{r}
library(tidyverse)
library(modelr)
library(mgcv)

library(SemiPar)

set.seed(1)
```

look at LIDAR data
```{r}
data("lidar")

lidar_df = 
  lidar %>% 
  as_tibble() %>% 
  mutate(id = row_number())
```

```{r}
lidar_df %>% 
  ggplot(aes(x = range, y = logratio)) +
  geom_point()
```

## Try to do CV

We'll compare 3 models -- one linear, one smooth, one wiggly

Construct training and testing df

```{r}
train_df = sample_frac(lidar_df, size = .8)

test_df = anti_join(lidar_df, train_df, by = "id")
```

Look at these
```{r}
ggplot(train_df, aes(x = range, y = logratio)) +
  geom_point() +
  geom_point(data = test_df, color = "red")
```

Fit three models

```{r}
linear_mod = lm(logratio ~ range, data = train_df)
smooth_mod = gam(logratio ~s(range), data = train_df)
wiggly_mod = gam(logratio ~ s(range, k = 30), sp = 10e-6, data = train_df)
```

Look at fits

```{r}
train_df %>% 
  add_predictions(linear_mod) %>% 
  ggplot(aes(x = range, y = logratio)) +
  geom_point() +
  # geom_point(data = test_df, color = "red") +
  geom_line(aes(y = pred), color = "red")
# a line is not complex enough

train_df %>% 
  add_predictions(wiggly_mod) %>% 
  ggplot(aes(x = range, y = logratio)) +
  geom_point() +
  # geom_point(data = test_df, color = "red") +
  geom_line(aes(y = pred), color = "red")

train_df %>% 
  add_predictions(smooth_mod) %>% 
  ggplot(aes(x = range, y = logratio)) +
  geom_point() +
  # geom_point(data = test_df, color = "red") +
  geom_line(aes(y = pred), color = "red")
```

Compare these numerically using RMSE

```{r}
rmse(linear_mod, test_df)

rmse(wiggly_mod, test_df)

rmse(smooth_mod, test_df)

# is the difference between wiggly and smooth models significant?
```

## Repeat the train / test split

```{r}
cv_df =
  crossv_mc(lidar_df, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
```


```{r}
cv_df |> pull(train) |> nth(1) |> as_tibble()

cv_df |> pull(test) |> nth(1) |> as_tibble()
```


Fit models, extract RMSEs

```{r}
cv_df = 
  cv_df |> 
  mutate(
    linear_mod  = map(train, \(df) lm(logratio ~ range, data = df)),
    smooth_mod  = map(train, \(df) gam(logratio ~ s(range), data = df)),
    wiggly_mod  = map(train, \(df) gam(logratio ~ s(range, k = 30), sp = 10e-6, data = df))) |> 
  mutate(
    rmse_linear = map2_dbl(linear_mod, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_smooth = map2_dbl(smooth_mod, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_wiggly = map2_dbl(wiggly_mod, test, \(mod, df) rmse(model = mod, data = df)))
```



## Nepalese children Df

```{r}
child_growth = read_csv("./data/nepalese_children.csv")

child_growth |> 
  ggplot(aes(x = weight, y = armc)) + 
  geom_point(alpha = .5)
```

```{r}
child_growth =
  child_growth |> 
  mutate(weight_cp7 = (weight > 7) * (weight - 7))
```

```{r}
linear_mod = lm(armc ~ weight, data = child_growth)
pwl_mod    = lm(armc ~ weight + weight_cp7, data = child_growth) # piecewise linear model
smooth_mod = gam(armc ~ s(weight), data = child_growth)
```

```{r}
child_growth |> 
  gather_predictions(linear_mod, pwl_mod, smooth_mod) |> 
  mutate(model = fct_inorder(model)) |> 
  ggplot(aes(x = weight, y = armc)) + 
  geom_point(alpha = .5) +
  geom_line(aes(y = pred), color = "red") + 
  facet_grid(~model)
```

```{r}
cv_df =
  crossv_mc(child_growth, 100) |> 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
```

```{r}
cv_df = 
  cv_df |> 
  mutate(
    linear_mod  = map(train, \(df) lm(armc ~ weight, data = df)),
    pwl_mod     = map(train, \(df) lm(armc ~ weight + weight_cp7, data = df)),
    smooth_mod  = map(train, \(df) gam(armc ~ s(weight), data = as_tibble(df)))) |> 
  mutate(
    rmse_linear = map2_dbl(linear_mod, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_pwl    = map2_dbl(pwl_mod, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_smooth = map2_dbl(smooth_mod, test, \(mod, df) rmse(model = mod, data = df)))
```

```{r}
cv_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") |> 
  mutate(model = fct_inorder(model)) |> 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```







