---
title: "linear_models"
author: "Xiaoni Xu"
date: "2024-11-07"
output: html_document
---
```{r, message = FALSE}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

Do some data cleaning

```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood # AMERICA FIRST
  ) %>% 
  filter(
    borough != "Staten Island"
  ) %>% 
  select(price, stars, borough, neighborhood, room_type) %>% 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  )
```

### Fit some models

Start relatively simple
```{r}
fit = lm(price ~ stars, data = nyc_airbnb)

summary(fit) # a lot of stuff comes out

names(summary(fit))

coef(fit)

broom::tidy(fit)

fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value)

fit %>% 
  broom::glance()
```

Try something a bit more complex
```{r}
fit =
  lm(price ~ stars + borough, data = nyc_airbnb)
# take all boroughs, take first one as reference, and make comparisons with that one. continue with the rest of the boroughs.

fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) %>% 
  knitr::kable(digits = 3)
```

